---
title: "Song Genre Exploratory Analysis"
author: "Lucius Bynum"
date: "4/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message=FALSE,
                      warning=FALSE,
                      fig.width=10)
library(readr)
library(ggplot2)
library(GGally)
library(dplyr)
```

```{r, cache=TRUE}
# load csv
csv_path = 'msd/features_vs_genre.csv'
df = read_csv(csv_path)
```

```{r}
str(df)
```

```{r}
summary(df)
```

```{r}
# plots
g = ggplot(df)

# genre v each feature
# remove year if 0
ggplot(df %>% filter(year > 0)) + geom_boxplot(aes(x=genre, y=year))
g + geom_boxplot(aes(x=genre, y=key))
# g + geom_histogram(aes(x=mode, fill=genre), bins=2)
g + geom_boxplot(aes(x=genre, y=mode))
g + geom_boxplot(aes(x=genre, y=time_signature))
g + geom_boxplot(aes(x=genre, y=duration))
g + geom_boxplot(aes(x=genre, y=end_of_fade_in))
g + geom_boxplot(aes(x=genre, y=loudness))
g + geom_boxplot(aes(x=genre, y=song_hotttnesss))
g + geom_boxplot(aes(x=genre, y=tempo))
```

```{r, fig.height=8}
# pairwise feature plots
features = df %>% dplyr::select(duration, end_of_fade_in, loudness, song_hotttnesss, tempo)
ggpairs(features)
```

